# Generated by Django 4.0.6 on 2022-09-14 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_rename_yazilar_yazilarlarmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YazilarlarModel',
            new_name='YazilarModel',
        ),
    ]
