# Generated by Django 4.0.6 on 2022-09-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_yorummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='İletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
            ],
            options={
                'verbose_name': 'iletişim',
                'verbose_name_plural': 'iletişim',
            },
        ),
    ]
