# Generated by Django 4.0.6 on 2022-09-14 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_i̇letisimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇letisimmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
