# Generated by Django 4.0.6 on 2022-09-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_rename_guncellenme_tarihi_yorummodel_duzenlenme_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇letisimmodel',
            options={},
        ),
    ]
