# Generated by Django 4.0.6 on 2022-09-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_i̇letisimmodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='İletisimModel',
            new_name='IletisimModel',
        ),
        migrations.AlterModelOptions(
            name='iletisimmodel',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterModelTable(
            name='iletisimmodel',
            table='iletisim',
        ),
    ]
