# Generated by Django 4.0.6 on 2022-09-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_rename_i̇letisimmodel_iletisimmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iletisimmodel',
            table=None,
        ),
    ]
